spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-tripai.cis7ml2gnvdm.ap-northeast-2.rds.amazonaws.com:3306/tripai?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: swimming005


  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.format_sql: true



jwt:
  header: Authorization
  secret: dHJpcGFpLXRlY2gtc3ByaW5nLWJvb3Qtand0LXR1dG9yaWFsLXNlY3JldC10cmlwYWktdGVjaC1zcHJpbmctYm9vdC1qd3QtdHV0b3JpYWwtc2VjcmV0
  refresh-token-secret: d29ybGQgbXkgbmFtZSBpcyBzc29uZyBoYWhhaGFoYWhhaGFoYSBydXJ1cnVydXJ1cnVydXJ1ZHNmc2Rmc2Rmc2Rmc2FkCg==
  access-token-validity-in-seconds: 3600 # 60 min
  refresh-token-validity-in-seconds: 86400
API-keys:
  TripAdvisor:
    API-Key: 8232d37af9mshbab18624a9b281ep13cb24jsn6c5477f7c3be
    API-Host: tripadvisor16.p.rapidapi.com
    SearchFlights-URL: https://tripadvisor16.p.rapidapi.com/api/v1/flights/searchFlights
  Restaurants:
    API-Key: 8232d37af9mshbab18624a9b281ep13cb24jsn6c5477f7c3be
    API-Host: restaurants222.p.rapidapi.com
    Typeahead-URL: https://restaurants222.p.rapidapi.com/typeahead
    Search-URL: https://restaurants222.p.rapidapi.com/search
  Booking:
    API-Key: 8232d37af9mshbab18624a9b281ep13cb24jsn6c5477f7c3be
    API-Host: booking-com15.p.rapidapi.com
    SearchHotelDestination-URL: https://booking-com15.p.rapidapi.com/api/v1/hotels/searchDestination
    SearchHotels-URL: https://booking-com15.p.rapidapi.com/api/v1/hotels/searchHotels
    SearchFlights-URL: https://booking-com15.p.rapidapi.com/api/v1/flights/searchFlights
  Tourist-Attraction:
    API-Key: 8232d37af9mshbab18624a9b281ep13cb24jsn6c5477f7c3be
    API-Host: tourist-attraction.p.rapidapi.com
    Typeahead-URL: https://tourist-attraction.p.rapidapi.com/typeahead
    Search-URL: https://tourist-attraction.p.rapidapi.com/search
OAuth2:
  Google-Client-Id: 32916786180-nstcqblsgb85inr47tm4lnjstm8dpb96.apps.googleusercontent.com